### ISSUE TITLE
SLACK integration

### ISSUE THREAD

**Issue by nharik25** [cloud-bulldozer/cerberus#116]
How do we add SLACK_API_TOKEN & SLACK_CHANNEL in the config.yaml file. Any example syntax would be helpful.
Thx

**Comment by gnunn1** [comment]
Just start cerberus with a bash file and add it to that, here is what I used (minus my actual slack info):

```
#!/bin/bash

echo "Starting Cerberus..."

export KUBECONFIG=/opt/cerberus/config/kubeconfig
export SLACK_API_TOKEN=XXXXXXXXXXXXXXXXXXXXXXXXXXXXX
export SLACK_CHANNEL=XXXXXXX

python3 /opt/cerberus/start_cerberus.py --config /opt/cerberus/config/config-home.yaml
```

**Comment by akshaymatoo** [comment]
If someone is running it through the container then set the env variables like  this

`docker run --env SLACK_API_TOKEN=<token> --env SLACK_CHANNEL=<channel_id> --name=cerberus --net=host -v /root/.kube/config:/root/.kube/config -v /root/cerberus/config.yaml:/root/cerberus/config/config.yaml -d quay.io/openshift-scale/cerberus:latest`

**Comment by lalan7** [comment]
You need to add permission in the slack Scopes for the Bot Token Scopes

```
calls:read
View information about ongoing and past calls

channels:read
View basic information about public channels in a workspace

chat:write
Send messages as @cerberus_bot

groups:read
View basic information about private channels that Cerberus Bot has been added to

im:read
View basic information about direct messages that Cerberus Bot has been added to

mpim:read
View basic information about group direct messages that Cerberus Bot has been added to
```

**Comment by chaitanyaenr** [comment]
Bot token scope need to modified to allow the cerberus slack app/bot to read/write to the channel like @lalan7 mentioned, it might be helpful to add it to the docs: https://github.com/cloud-bulldozer/cerberus/blob/master/docs/slack.md. 

@lalan7 Do you want to create a PR for it?

**Comment by lalan7** [comment]
@chaitanyaenr Perfect let me create PR for it.

**Comment by amitsagtani97** [comment]
Issue fixed! Closing it
