### ISSUE TITLE
Issue with custom-checks 

### ISSUE THREAD

**Issue by juliemathew** [cloud-bulldozer/cerberus#117]
I would like to contribute to the feature of adding **custom-checks**, so explored this a bit.

While testing with my custom-check file '/root/cerberus/custom_checks/custom_check_res_usage.py', 
Cerberus shows this error message in the report 
```
2021-02-10 01:36:12,589 [INFO] Encountered issues in cluster. Hence, setting the go/no-go signal to false
2021-02-10 01:36:12,590 [INFO] Exception: Empty module name
```

Issues:
1.  Why this Exception: Empty module name?
2.   It says that the signal is set to 'False', however the failure details are not getting notified in the slack channel that I have enabled.

Can we discuss this?   @yashashreesuresh  @chaitanyaenr  
Please let me know how to take this discussion forward? via email / slack?
Thanks.

**Comment by yashashreesuresh** [comment]
Hey @juliemathew,

Regarding the issues you encountered,
1. Is the custom_checks section of your config.yaml file set up like this [here](https://github.com/cloud-bulldozer/cerberus/pull/89/files#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5R61)?
If yes, can you please show how your custom_check_res_usage.py and config.yaml files.
2. Custom check failures are not reported on the slack channel as this functionality hasn't been added yet (Currently Cerberus supports reporting of pods, nodes and cluster operator failures only).

**Comment by Rajalakshmi-Girish** [comment]
@juliemathew below changes to `start_cerberus.py` could get my custom_check failure notifications to slack:
```
@@ -326,7 +326,7 @@ def main(cfg):
                 # Report failures in a slack channel
                 if not watch_nodes_status or not watch_namespaces_status or \
-                        not watch_cluster_operators_status:
+                        not watch_cluster_operators_status or not check_returns:
                     if slack_integration:
                         slackcli.slack_logging(cluster_info, iteration, watch_nodes_status,
                                                failed_nodes, watch_cluster_operators_status,
```

**Comment by juliemathew** [comment]
> 
> 
> @juliemathew below changes to `start_cerberus.py` could get my custom_check failure notifications to slack:
> 
> ```
> @@ -326,7 +326,7 @@ def main(cfg):
>                  # Report failures in a slack channel
>                  if not watch_nodes_status or not watch_namespaces_status or \
> -                        not watch_cluster_operators_status:
> +                        not watch_cluster_operators_status or not check_returns:
>                      if slack_integration:
>                          slackcli.slack_logging(cluster_info, iteration, watch_nodes_status,
>                                                 failed_nodes, watch_cluster_operators_status,
> ```

Yes it worked for me too.
Thank you @Rajalakshmi-Girish

**Comment by chaitanyaenr** [comment]
Thanks to @Rajalakshmi-Girish, custom checks status should be part of the slack reporting now: https://github.com/cloud-bulldozer/cerberus/pull/119. 

@juliemathew Let us know if the suggested changes did not work for you, we can definitely work with you on resolving the issues. Thanks.

**Comment by juliemathew** [comment]
> 
> 
> Thanks to @Rajalakshmi-Girish, custom checks status should be part of the slack reporting now: #119.
> 
> @juliemathew Let us know if the suggested changes did not work for you, we can definitely work with you on resolving the issues. Thanks.

Tested the modified code, it works for me. Thanks @chaitanyaenr
