### ISSUE TITLE
Watching master_schedulable_status should be optional

### ISSUE THREAD

**Issue by Rajalakshmi-Girish** [cloud-bulldozer/cerberus#122]
Cerberus executes `kubecli.process_master_taint` to watch the schedulable status of master.
https://github.com/cloud-bulldozer/cerberus/blob/master/start_cerberus.py#L212
https://github.com/cloud-bulldozer/cerberus/blob/master/cerberus/kubernetes/client.py#L317

In certain hosted environments, the master node's information is not available. Thus the call to list nodes with label `"node-role.kubernetes.io/master" ` cannot be expected to succeed in all environments,
 **Call to list nodes with above label:** https://github.com/cloud-bulldozer/cerberus/blob/master/start_cerberus.py#L140
Thus we encountered exception in https://github.com/cloud-bulldozer/cerberus/blob/master/cerberus/kubernetes/client.py#L302 while cerberus was trying to check master node's schedulable status.
```
2021-03-08 10:16:09,925 [INFO] Cerberus is not monitoring nodes, so setting the status to True and assuming that the nodes are ready
2021-03-08 10:16:10,160 [INFO] Encountered issues in cluster. Hence, setting the go/no-go signal to false
2021-03-08 10:16:10,160 [INFO] Exception: 'name'

2021-03-08 10:16:10,361 [INFO] Cerberus is not monitoring nodes, so setting the status to True and assuming that the nodes are ready
2021-03-08 10:16:10,398 [INFO] HTTP requests served: 0

2021-03-08 10:16:10,399 [INFO] Encountered issues in cluster. Hence, setting the go/no-go signal to false
2021-03-08 10:16:10,399 [INFO] Exception: local variable 'custom_checks_imports' referenced before assignment
```

**Comment by Rajalakshmi-Girish** [comment]
Below would be the changes needed for making this feature optional:
**Changes to cerberus/start_cerberus.py:**
```

>         watch_schedulable_masters = config["cerberus"].get("watch_schedulable_masters", True)
140c141,143
<         master_nodes = kubecli.list_nodes("node-role.kubernetes.io/master")
---
>         master_nodes = []
>         if watch_schedulable_masters:
>                 master_nodes = kubecli.list_nodes("node-role.kubernetes.io/master")
212a216
>                                                       watch_schedulable_masters,
root@sajauddin-dev:~/rajalakshmi/fork/test-infra/config/prow/cluster#
```

**Changes in cerberus/cerberus/kubernetes/client.py:**
```


< def process_master_taint(master_nodes, iteration, iter_track_time):
---
> def process_master_taint(watch_schedulable_masters, master_nodes, iteration, iter_track_time):
319,322c319,323
<     if iteration % 10 == 1:
<         check_taint_start_time = time.time()
<         schedulable_masters = check_master_taint(master_nodes)
<         iter_track_time['check_master_taint'] = time.time() - check_taint_start_time
---
>     if watch_schedulable_masters:
>         if iteration % 10 == 1:
>             check_taint_start_time = time.time()
>             schedulable_masters = check_master_taint(master_nodes)
>             iter_track_time['check_master_taint'] = time.time() - check_taint_start_time
```

**Comment by Rajalakshmi-Girish** [comment]
@chaitanyaenr @yashashreesuresh ^^

**Comment by chaitanyaenr** [comment]
@Rajalakshmi-Girish Thanks for reporting the issue. We will take a look and get back to you.

**Comment by chaitanyaenr** [comment]
@Rajalakshmi-Girish is the kubecli.list_nodes("node-role.kubernetes.io/master") call failing because of the user permissions on the cluster?

**Comment by Rajalakshmi-Girish** [comment]
`kubecli.list_nodes("node-role.kubernetes.io/master")`  returned empty list from IKS cluster. @mkumatag was this beacuse of lack of permissions or can we not expect such labels on hosted environment. Can you please clarify?
The exception was from https://github.com/cloud-bulldozer/cerberus/blob/master/cerberus/kubernetes/client.py#L302  due to empty list of master nodes.

**Comment by mkumatag** [comment]
> `kubecli.list_nodes("node-role.kubernetes.io/master")` returned empty list from IKS cluster. @mkumatag was this beacuse of lack of permissions or can we not expect such labels on hosted environment. Can you please clarify?

It is not a lack of permission, in the hosted environments like IKS(IBM's Kubernetes Service), master nodes are not exposed to the user and does not list the master nodes when user runs: `kubectl get nodes`
> The exception was from https://github.com/cloud-bulldozer/cerberus/blob/master/cerberus/kubernetes/client.py#L302 due to empty list of master nodes.

**Comment by mkumatag** [comment]
> @Rajalakshmi-Girish is the kubecli.list_nodes("node-role.kubernetes.io/master") call failing because of the user permissions on the cluster?

this will return the empty list because there are no nodes with that label when you query for a node_list API.

**Comment by chaitanyaenr** [comment]
@Rajalakshmi-Girish, @amitsagtani97 patched the code to have optional master node schedulable checks: https://github.com/cloud-bulldozer/cerberus/pull/127. Closing the issue, please feel free to reopen if something needs to be changed. Thanks.
