### ISSUE TITLE
Cerberus stuck during kraken cluster shut down scenario

### ISSUE THREAD

**Issue by paigerube14** [cloud-bulldozer/cerberus#143]
I have had cerberus running during my testing of adding a cluster shut down scenario to kraken. Every time cerberus gets stuck when it can no longer execute any of the commands. It just hangs.

```
The connection to the server api.qe-pr-awsnt.qe.devcluster.openshift.com:6443 was refused - did you specify the right host or port?
2021-06-14 14:22:03,433 [ERROR] Failed to run kubectl get pods --chunk-size 250 -n openshift-sdn -o json
The connection to the server api.qe-pr-awsnt.qe.devcluster.openshift.com:6443 was refused - did you specify the right host or port?
2021-06-14 14:22:03,867 [ERROR] Failed to run kubectl get pods --chunk-size 250 -n openshift-monitoring -o json
The connection to the server api.qe-pr-awsnt.qe.devcluster.openshift.com:6443 was refused - did you specify the right host or port?
2021-06-14 14:22:04,178 [ERROR] Failed to run kubectl get pods --chunk-size 250 -n openshift-ingress -o json
The connection to the server api.qe-pr-awsnt.qe.devcluster.openshift.com:6443 was refused - did you specify the right host or port?
2021-06-14 14:22:04,448 [ERROR] Failed to run kubectl get pods --chunk-size 250 -n openshift-kube-scheduler -o json
The connection to the server api.qe-pr-awsnt.qe.devcluster.openshift.com:6443 was refused - did you specify the right host or port?
2021-06-14 14:22:04,498 [ERROR] Failed to run kubectl get pods --chunk-size 250 -n openshift-kube-apiserver -o json
```

I'm not sure if we just need to add a timeout to the commands if the response doesn't come back or need a different way around this but it is very inconvenient and the only way I've found is to kill cerberus and restart it.

**Comment by chaitanyaenr** [comment]
@paigerube14 and I discussed offline, we would need to re-initialize the kubernetes client as the kubeconfig changes when the cluster is brought back up after shutting it down and the kubeconfig initialized at the start of the cerberus run is no longer valid.

**Comment by paigerube14** [comment]
I found the option [ --request-timeout](https://kubernetes.io/docs/reference/kubectl/kubectl/) in the kubernetes documentation and also tried adding a timeout to the invoke function and it's still getting stuck after a couple of failed commands. 
The hard part is it seems like one of the commands is not returning so it's just getting stuck, trying to find which command/set of commands it is

**Comment by paigerube14** [comment]
Closing with fix from PR: https://github.com/cloud-bulldozer/cerberus/pull/144
